version: "3.8"

services:
  bridge-checker:
    build: .
    container_name: celestia-bridge-health-checker-discord
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
