version: "3.8"

services:
  bridge-checker:
    build: .
    container_name: celestia-bridge-health-checker-discord
    ports:
      - "3000:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
    restart: unless-stopped
